### ISSUE TITLE
commenting code in python 

### ISSUE THREAD

**Issue by ad3429** [ChuckleWacker/pwp-capstones#1]
https://github.com/ChuckleWacker/pwp-capstones/blob/master/Final/Week9_TomeRater_Project.py#L19-L26

It seems you have a lot of comments throughout your python code. Commenting is generally a very good practice especially in the early stages of your development, however as you become more advanced you should only comment parts that you believe need clarification or explaining. Commenting parts that are self-explanatory can actually at times distract from the main parts of the code and make your code less readable. 

For now though, good job getting in the practice of commenting, which many learners forget to do completely! :)

**Comment by ChuckleWacker** [comment]
Cleared out some unneeded comments.
