### ISSUE TITLE
another way to write create_book function 

### ISSUE THREAD

**Issue by ad3429** [ChuckleWacker/pwp-capstones#2]
https://github.com/ChuckleWacker/pwp-capstones/blob/master/Final/Week9_TomeRater_Project.py#L109-L111

The way you wrote this function is fine, but another neat way to write this to save an extra line would be something like:

```
def create_book(self, title, isbn):
    return Book(title, isbn)

```

**Comment by ChuckleWacker** [comment]
This is way cleaner, updated code to reflect a more DRY approach.
