### ISSUE TITLE
set highest_value to negative infinity

### ISSUE THREAD

**Issue by ad3429** [ChuckleWacker/pwp-capstones#3]
https://github.com/ChuckleWacker/pwp-capstones/blob/master/Final/Week9_TomeRater_Project.py#L150

It seems you set the highest_value to 0 for your get_most_read_book function, however it's considered good practice to initialize values like this to impossible values such as negative infinity. Thus you can do something like:

`highest_value = float("-inf")`

**Comment by ChuckleWacker** [comment]
I was wondering this too, I used this method variable to track a count for finding the highest, to me it makes sense but I will consider this alternate approach for others to be able to read my code.
